### ISSUE TITLE
[BUG] Unable to convert provided checkpoint

### ISSUE THREAD

**Issue by CPA872** [pan-x-c/EE-LLM#5]
Hello!

I am trying to run ee_inference using the provided checkpoint. I have a 2 A100 setup therefore I needed to convert the checkpoint. But I am getting a "bus error" on my system. I have tried using other systems but have the same result. Would appreciate any help!

**Describe the bug**
After downloading the provided checkpoint from modelscope (EE-LLM-1B-dj-refine-300B), cannot convert to TP=1  PP=2 using provided convert_parallelism.sh

**To Reproduce**
```bash
#!/bin/bash

# load/save dir
LOAD_DIR=/workspace/ckpt/EE-LLM-1B-dj-refine-300B           # to ROOT 
SAVE_DIR=/workspace/ckpt/EE-LLM-1B-dj-refine-300B-pp1

# target parallelism
TP=1
PP=2

CUR_DIR=$(cd $(dirname "$0") && pwd)
MEGATRON_ROOT_PATH=$(cd "$CUR_DIR/.." && pwd)
cd $MEGATRON_ROOT_PATH


python $MEGATRON_ROOT_PATH/tools/checkpoint/util.py --model-type EarlyExitGPT --load-dir $LOAD_DIR --save-dir $SAVE_DIR --target-tensor-parallel-size $TP --target-pipeline-parallel-size $PP --megatron-path $MEGATRON_ROOT_PATH
```

**Expected behavior**

**Stack trace/logs**
```
root@ee-llm-2a100:/workspace/EE-LLM/tools# bash convert_parallelism.sh 
Loaded loader_megatron as the loader.
Loaded saver_megatron as the saver.
Starting saver...
Starting loader...
Zarr-based strategies will not be registered because of missing packages
Zarr-based strategies will not be registered because of missing packages
Setting num_layers to 24 from checkpoint
Setting hidden_size to 2048 from checkpoint
Setting ffn_hidden_size to 5440 from checkpoint
Setting seq_length to 2048 from checkpoint
Setting num_attention_heads to 32 from checkpoint
Setting num_query_groups to 1 from checkpoint
Setting group_query_attention to False from checkpoint
Setting kv_channels to 64 from checkpoint
Setting max_position_embeddings to 2048 from checkpoint
Setting position_embedding_type to rope from checkpoint
Setting add_position_embedding to True from checkpoint
Setting use_rotary_position_embeddings to False from checkpoint
Setting rotary_percent to 1.0 from checkpoint
Setting add_bias_linear to False from checkpoint
Setting swiglu to True from checkpoint
Setting untie_embeddings_and_output_weights to False from checkpoint
Setting apply_layernorm_1p to False from checkpoint
Setting normalization to LayerNorm from checkpoint
Setting tokenizer_type to SentencePieceTokenizer from checkpoint
Setting padded_vocab_size to 32128 from checkpoint
Setting make_vocab_size_divisible_by to 128 from checkpoint
Setting exit_layer_nums to [6, 12] from checkpoint
Setting exit_layer_weight to [0.25, 0.5] from checkpoint
Setting use_exit_mlp to False from checkpoint
Setting use_exit_block to False from checkpoint
Setting use_exit_norm to False from checkpoint
Setting untie_exit_output_weights to False from checkpoint
Setting pre_exit to False from checkpoint
Setting tensor_model_parallel_size to 1 from checkpoint
Setting pipeline_model_parallel_size to 4 from checkpoint
Checkpoint did not provide arguments virtual_pipeline_model_parallel_size
Checkpoint did not provide arguments num_layers_per_virtual_pipeline_stage
using world size: 4, data-parallel-size: 1, tensor-model-parallel size: 1, pipeline-model-parallel size: 4 
setting global batch size to 1
using torch.float32 for parameters ...
------------------------ arguments ------------------------
  accumulate_allreduce_grads_in_fp32 .............. False
  adam_beta1 ...................................... 0.9
  adam_beta2 ...................................... 0.999
  adam_eps ........................................ 1e-08
  add_bias_linear ................................. False
  add_position_embedding .......................... False
  adlr_autoresume ................................. False
  adlr_autoresume_interval ........................ 1000
  apply_layernorm_1p .............................. False
  apply_query_key_layer_scaling ................... False
  apply_residual_connection_post_layernorm ........ False
  async_tensor_model_parallel_allreduce ........... False
  attention_dropout ............................... 0.1
  attention_softmax_in_fp32 ....................... False
  backward_forward_ratio .......................... 2.0
  barrier_with_L1_time ............................ True
  bert_binary_head ................................ True
  bert_embedder_type .............................. megatron
  bert_load ....................................... None
  bf16 ............................................ False
  bias_dropout_fusion ............................. False
  bias_gelu_fusion ................................ False
  biencoder_projection_dim ........................ 0
  biencoder_shared_query_context_model ............ False
  block_data_path ................................. None
  check_for_nan_in_loss_and_grad .................. True
  classes_fraction ................................ 1.0
  clip_grad ....................................... 1.0
  consumed_train_samples .......................... 0
  consumed_valid_samples .......................... 0
  data_cache_path ................................. None
  data_parallel_random_init ....................... False
  data_parallel_size .............................. 1
  data_path ....................................... None
  data_per_class_fraction ......................... 1.0
  data_sharding ................................... True
  dataloader_type ................................. single
  decoder_num_layers .............................. None
  decoder_seq_length .............................. None
  delay_grad_reduce ............................... True
  dino_bottleneck_size ............................ 256
  dino_freeze_last_layer .......................... 1
  dino_head_hidden_size ........................... 2048
  dino_local_crops_number ......................... 10
  dino_local_img_size ............................. 96
  dino_norm_last_layer ............................ False
  dino_teacher_temp ............................... 0.07
  dino_warmup_teacher_temp ........................ 0.04
  dino_warmup_teacher_temp_epochs ................. 30
  distribute_saved_activations .................... False
  distributed_backend ............................. nccl
  distributed_timeout_minutes ..................... 10
  embedding_path .................................. None
  empty_unused_memory_level ....................... 0
  encoder_num_layers .............................. 24
  encoder_seq_length .............................. 2048
  end_weight_decay ................................ 0.01
  eod_mask_loss ................................... False
  eval_interval ................................... 1000
  eval_iters ...................................... 100
  evidence_data_path .............................. None
  exit_duration_in_mins ........................... None
  exit_interval ................................... None
  exit_layer_nums ................................. [6, 12]
  exit_layer_temperature .......................... [1.0, 1.0]
  exit_layer_weight ............................... [0.25, 0.5]
  exit_layer_weight_init .......................... [0.0, 0.0]
  exit_layer_weight_warmup_iters .................. 0
  exit_layer_weight_warmup_style .................. linear
  exit_on_missing_checkpoint ...................... False
  exit_signal_handler ............................. False
  expert_model_parallel_size ...................... 1
  expert_parallel ................................. False
  ffn_hidden_size ................................. 5440
  fill_explicit_bubbles ........................... False
  finetune ........................................ False
  fp16 ............................................ False
  fp16_lm_cross_entropy ........................... False
  fp32_residual_connection ........................ False
  fp8 ............................................. None
  fp8_amax_compute_algo ........................... most_recent
  fp8_amax_history_len ............................ 1
  fp8_interval .................................... 1
  fp8_margin ...................................... 0
  fp8_wgrad ....................................... True
  global_batch_size ............................... 1
  gradient_accumulation_fusion .................... True
  group_query_attention ........................... False
  head_lr_mult .................................... 1.0
  hidden_dropout .................................. 0.1
  hidden_size ..................................... 2048
  hysteresis ...................................... 2
  ict_head_size ................................... None
  ict_load ........................................ None
  img_h ........................................... 224
  img_w ........................................... 224
  indexer_batch_size .............................. 128
  indexer_log_interval ............................ 1000
  inference_batch_times_seqlen_threshold .......... 512
  init_method_std ................................. 0.02
  init_method_xavier_uniform ...................... False
  initial_loss_scale .............................. 4294967296
  iter_per_epoch .................................. 1250
  iteration ....................................... 72000
  kv_channels ..................................... 64
  lazy_mpu_init ................................... None
  load ............................................ /workspace/ckpt/EE-LLM-1B-dj-refine-300B
  load_iteration .................................. 0
  local_rank ...................................... None
  log_batch_size_to_tracker ....................... False
  log_interval .................................... 100
  log_learning_rate_to_tracker .................... True
  log_loss_scale_to_tracker ....................... True
  log_memory_to_tracker ........................... False
  log_num_zeros_in_grad ........................... False
  log_params_norm ................................. False
  log_timers_to_tracker ........................... False
  log_validation_ppl_to_tracker ................... False
  log_world_size_to_tracker ....................... False
  loss_scale ...................................... None
  loss_scale_window ............................... 1000
  lr .............................................. None
  lr_decay_iters .................................. None
  lr_decay_samples ................................ None
  lr_decay_style .................................. linear
  lr_warmup_fraction .............................. None
  lr_warmup_init .................................. 0.0
  lr_warmup_iters ................................. 0
  lr_warmup_samples ............................... 0
  make_vocab_size_divisible_by .................... 128
  mask_factor ..................................... 1.0
  mask_prob ....................................... 0.15
  mask_type ....................................... random
  masked_softmax_fusion ........................... False
  max_position_embeddings ......................... 2048
  max_tokens_to_oom ............................... 12000
  merge_file ...................................... None
  micro_batch_size ................................ 1
  min_loss_scale .................................. 1.0
  min_lr .......................................... 0.0
  mmap_warmup ..................................... False
  model_spec ...................................... None
  no_load_optim ................................... True
  no_load_rng ..................................... True
  no_persist_layer_norm ........................... False
  no_save_optim ................................... True
  no_save_rng ..................................... True
  norm_epsilon .................................... 1e-05
  normalization ................................... LayerNorm
  num_attention_heads ............................. 32
  num_channels .................................... 3
  num_classes ..................................... 1000
  num_experts ..................................... None
  num_fill_cooldown_microbatches .................. None
  num_fill_warmup_microbatches .................... None
  num_layers ...................................... 24
  num_layers_per_virtual_pipeline_stage ........... None
  num_query_groups ................................ 1
  num_workers ..................................... 2
  onnx_safe ....................................... None
  openai_gelu ..................................... False
  optimizer ....................................... adam
  output_bert_embeddings .......................... False
  overlap_grad_reduce ............................. False
  overlap_p2p_comm ................................ False
  override_opt_param_scheduler .................... False
  padded_vocab_size ............................... 32128
  params_dtype .................................... torch.float32
  patch_dim ....................................... 16
  perform_initialization .......................... False
  pipeline_model_parallel_size .................... 4
  pipeline_model_parallel_split_rank .............. None
  position_embedding_type ......................... rope
  pre_exit ........................................ False
  profile ......................................... False
  profile_ranks ................................... [0]
  profile_step_end ................................ 12
  profile_step_start .............................. 10
  query_in_block_prob ............................. 0.1
  rampup_batch_size ............................... None
  rank ............................................ 0
  recompute_granularity ........................... None
  recompute_method ................................ None
  recompute_num_layers ............................ None
  reset_attention_mask ............................ False
  reset_position_ids .............................. False
  retriever_report_topk_accuracies ................ []
  retriever_score_scaling ......................... False
  retriever_seq_length ............................ 256
  retro_add_retriever ............................. False
  retro_cyclic_train_iters ........................ None
  retro_encoder_attention_dropout ................. 0.1
  retro_encoder_hidden_dropout .................... 0.1
  retro_encoder_layers ............................ 2
  retro_num_neighbors ............................. 2
  retro_num_retrieved_chunks ...................... 2
  retro_return_doc_ids ............................ False
  retro_workdir ................................... None
  rotary_percent .................................. 1.0
  rotary_seq_len_interpolation_factor ............. None
  sample_rate ..................................... 1.0
  save ............................................ None
  save_interval ................................... None
  scatter_gather_tensors_in_pipeline .............. True
  seed ............................................ 1234
  seq_length ...................................... 2048
  sequence_parallel ............................... False
  sgd_momentum .................................... 0.9
  short_seq_prob .................................. 0.1
  skip_train ...................................... False
  split ........................................... 969, 30, 1
  squared_relu .................................... False
  standalone_embedding_stage ...................... False
  start_weight_decay .............................. 0.01
  swiglu .......................................... True
  swin_backbone_type .............................. tiny
  tensor_model_parallel_size ...................... 1
  tensorboard_dir ................................. None
  tensorboard_queue_size .......................... 1000
  test_data_path .................................. None
  timing_log_level ................................ 0
  timing_log_option ............................... minmax
  titles_data_path ................................ None
  tokenizer_model ................................. None
  tokenizer_type .................................. SentencePieceTokenizer
  tracker_log_interval ............................ 1
  train_data_path ................................. None
  train_iters ..................................... None
  train_samples ................................... None
  transformer_impl ................................ local
  transformer_pipeline_model_parallel_size ........ 4
  tune_exit ....................................... False
  tune_exit_pipeline_parallel_size ................ 1
  untie_embeddings_and_output_weights ............. False
  untie_exit_output_weights ....................... False
  use_checkpoint_args ............................. False
  use_checkpoint_opt_param_scheduler .............. False
  use_cpu_initialization .......................... True
  use_distributed_optimizer ....................... False
  use_dynamic_exit_layer_weight ................... False
  use_exit_block .................................. False
  use_exit_mlp .................................... False
  use_exit_norm ................................... False
  use_flash_attn .................................. False
  use_mcore_models ................................ False
  use_one_sent_docs ............................... False
  use_ring_exchange_p2p ........................... False
  use_rotary_position_embeddings .................. False
  valid_data_path ................................. None
  variable_seq_lengths ............................ False
  virtual_pipeline_model_parallel_size ............ None
  vision_backbone_type ............................ vit
  vision_pretraining .............................. False
  vision_pretraining_type ......................... classify
  vocab_extra_ids ................................. 0
  vocab_file ...................................... None
  vocab_size ...................................... None
  wandb_exp_name .................................. default
  wandb_group ..................................... None
  wandb_project ................................... None
  wandb_save_dir .................................. 
  weight_decay .................................... 0.01
  weight_decay_incr_style ......................... constant
  world_size ...................................... 4
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 1
building EarlyExitGPT model ...
 loading checkpoint from /workspace/ckpt/EE-LLM-1B-dj-refine-300B at iteration 72000
 checkpoint version 3.0
  successfully loaded checkpoint from /workspace/ckpt/EE-LLM-1B-dj-refine-300B at iteration 72000
Overwriting default ffn_hidden_size value None with value from checkpoint 5440.
Overwriting default kv_channels value None with value from checkpoint 64.
Overwriting default swiglu value False with value from checkpoint True.
Overwriting default attention_dropout value 0.1 with value from checkpoint 0.0.
Overwriting default hidden_dropout value 0.1 with value from checkpoint 0.0.
Overwriting default weight_decay value 0.01 with value from checkpoint 0.1.
Overwriting default adam_beta2 value 0.999 with value from checkpoint 0.95.
Overwriting default micro_batch_size value 1 with value from checkpoint 4.
Overwriting default global_batch_size value None with value from checkpoint 2048.
Overwriting default log_interval value 100 with value from checkpoint 5.
Overwriting default use_flash_attn value False with value from checkpoint True.
Overwriting default dataloader_type value None with value from checkpoint single.
Overwriting default init_method_std value 0.02 with value from checkpoint 0.01.
Overwriting default lr value None with value from checkpoint 0.0002.
Overwriting default lr_decay_style value linear with value from checkpoint cosine.
Overwriting default min_lr value 0.0 with value from checkpoint 2e-05.
Overwriting default load value None with value from checkpoint /home/data/shared/checkpoints/MET-EXP/1F1B-MET-1B-2-EXIT-6-12-0.25-0.5-300B.
Overwriting default bf16 value False with value from checkpoint True.
Overwriting default apply_query_key_layer_scaling value False with value from checkpoint True.
Overwriting default accumulate_allreduce_grads_in_fp32 value False with value from checkpoint True.
Overwriting default local_rank value None with value from checkpoint 0.
Overwriting default eval_iters value 100 with value from checkpoint 10.
Overwriting default eval_interval value 1000 with value from checkpoint 1200.
Overwriting default data_path value None with value from checkpoint ['0.0362', '/home/data/shared/dataset/data_juicer/mmap/redpajama-arxiv/all', '0.0657', '/home/data/shared/dataset/data_juicer/mmap/redpajama-book/all', '0.2264', '/home/data/shared/dataset/data_juicer/mmap/redpajama-c4/all', '0.4491', '/home/data/shared/dataset/data_juicer/mmap/redpajama-cc/all', '0.0246', '/home/data/shared/dataset/data_juicer/mmap/redpajama-pile-stackexchange/all', '0.0810', '/home/data/shared/dataset/data_juicer/mmap/redpajama-stack-code/all', '0.0548', '/home/data/shared/dataset/data_juicer/mmap/redpajama-wiki/all', '0.0010', '/home/data/shared/dataset/data_juicer/mmap/the-pile-europarl/all', '0.0162', '/home/data/shared/dataset/data_juicer/mmap/the-pile-freelaw/all', '0.0006', '/home/data/shared/dataset/data_juicer/mmap/the-pile-hackernews/all', '0.0005', '/home/data/shared/dataset/data_juicer/mmap/the-pile-nih/all', '0.0006', '/home/data/shared/dataset/data_juicer/mmap/the-pile-philpaper/all', '0.0065', '/home/data/shared/dataset/data_juicer/mmap/the-pile-pubmed-abstract/all', '0.0318', '/home/data/shared/dataset/data_juicer/mmap/the-pile-pubmed-central/all', '0.0050', '/home/data/shared/dataset/data_juicer/mmap/the-pile-uspto/all'].
Overwriting default split value 969, 30, 1 with value from checkpoint 990,9,1.
Overwriting default padded_vocab_size value None with value from checkpoint 32128.
Overwriting default log_timers_to_tracker value False with value from checkpoint True.
Overwriting default wandb_project value None with value from checkpoint MET-EXP.
Overwriting default wandb_group value None with value from checkpoint 1F1B-MET-1B-2-EXIT-6-12-0.25-0.5-300B.
Overwriting default exit_layer_weight_init value [] with value from checkpoint [0.0, 0.0].
Overwriting default exit_layer_temperature value [] with value from checkpoint [1.0, 1.0].
Overwriting default num_fill_warmup_microbatches value None with value from checkpoint 0.
Overwriting default num_fill_cooldown_microbatches value None with value from checkpoint 0.
Checkpoint had argument transformer_pipeline_model_parallel_size but new arguments does not have this.
Checkpoint had argument data_parallel_size but new arguments does not have this.
Checkpoint had argument consumed_train_samples but new arguments does not have this.
Checkpoint had argument consumed_valid_samples but new arguments does not have this.
Checkpoint had argument variable_seq_lengths but new arguments does not have this.
Checkpoint had argument model_type but new arguments does not have this.
using world size: 2, data-parallel-size: 1, tensor-model-parallel size: 1, pipeline-model-parallel size: 2 
using torch.bfloat16 for parameters ...
------------------------ arguments ------------------------
  accumulate_allreduce_grads_in_fp32 .............. True
  adam_beta1 ...................................... 0.9
  adam_beta2 ...................................... 0.95
  adam_eps ........................................ 1e-08
  add_bias_linear ................................. False
  add_position_embedding .......................... False
  adlr_autoresume ................................. False
  adlr_autoresume_interval ........................ 1000
  apply_layernorm_1p .............................. False
  apply_query_key_layer_scaling ................... True
  apply_residual_connection_post_layernorm ........ False
  async_tensor_model_parallel_allreduce ........... False
  attention_dropout ............................... 0.0
  attention_softmax_in_fp32 ....................... False
  backward_forward_ratio .......................... 2.0
  barrier_with_L1_time ............................ True
  bert_binary_head ................................ True
  bert_embedder_type .............................. megatron
  bert_load ....................................... None
  bf16 ............................................ True
  bias_dropout_fusion ............................. False
  bias_gelu_fusion ................................ False
  biencoder_projection_dim ........................ 0
  biencoder_shared_query_context_model ............ False
  block_data_path ................................. None
  check_for_nan_in_loss_and_grad .................. True
  classes_fraction ................................ 1.0
  clip_grad ....................................... 1.0
  consumed_train_samples .......................... 0
  consumed_valid_samples .......................... 0
  data_cache_path ................................. None
  data_parallel_random_init ....................... False
  data_parallel_size .............................. 1
  data_path ....................................... ['0.0362', '/home/data/shared/dataset/data_juicer/mmap/redpajama-arxiv/all', '0.0657', '/home/data/shared/dataset/data_juicer/mmap/redpajama-book/all', '0.2264', '/home/data/shared/dataset/data_juicer/mmap/redpajama-c4/all', '0.4491', '/home/data/shared/dataset/data_juicer/mmap/redpajama-cc/all', '0.0246', '/home/data/shared/dataset/data_juicer/mmap/redpajama-pile-stackexchange/all', '0.0810', '/home/data/shared/dataset/data_juicer/mmap/redpajama-stack-code/all', '0.0548', '/home/data/shared/dataset/data_juicer/mmap/redpajama-wiki/all', '0.0010', '/home/data/shared/dataset/data_juicer/mmap/the-pile-europarl/all', '0.0162', '/home/data/shared/dataset/data_juicer/mmap/the-pile-freelaw/all', '0.0006', '/home/data/shared/dataset/data_juicer/mmap/the-pile-hackernews/all', '0.0005', '/home/data/shared/dataset/data_juicer/mmap/the-pile-nih/all', '0.0006', '/home/data/shared/dataset/data_juicer/mmap/the-pile-philpaper/all', '0.0065', '/home/data/shared/dataset/data_juicer/mmap/the-pile-pubmed-abstract/all', '0.0318', '/home/data/shared/dataset/data_juicer/mmap/the-pile-pubmed-central/all', '0.0050', '/home/data/shared/dataset/data_juicer/mmap/the-pile-uspto/all']
  data_per_class_fraction ......................... 1.0
  data_sharding ................................... True
  dataloader_type ................................. single
  decoder_num_layers .............................. None
  decoder_seq_length .............................. None
  delay_grad_reduce ............................... True
  dino_bottleneck_size ............................ 256
  dino_freeze_last_layer .......................... 1
  dino_head_hidden_size ........................... 2048
  dino_local_crops_number ......................... 10
  dino_local_img_size ............................. 96
  dino_norm_last_layer ............................ False
  dino_teacher_temp ............................... 0.07
  dino_warmup_teacher_temp ........................ 0.04
  dino_warmup_teacher_temp_epochs ................. 30
  distribute_saved_activations .................... False
  distributed_backend ............................. nccl
  distributed_timeout_minutes ..................... 10
  embedding_path .................................. None
  empty_unused_memory_level ....................... 0
  encoder_num_layers .............................. 24
  encoder_seq_length .............................. 2048
  end_weight_decay ................................ 0.1
  eod_mask_loss ................................... False
  eval_interval ................................... 1200
  eval_iters ...................................... 10
  evidence_data_path .............................. None
  exit_duration_in_mins ........................... None
  exit_interval ................................... None
  exit_layer_nums ................................. [6, 12]
  exit_layer_temperature .......................... [1.0, 1.0]
  exit_layer_weight ............................... [0.25, 0.5]
  exit_layer_weight_init .......................... [0.0, 0.0]
  exit_layer_weight_warmup_iters .................. 0
  exit_layer_weight_warmup_style .................. linear
  exit_on_missing_checkpoint ...................... False
  exit_signal_handler ............................. False
  expert_model_parallel_size ...................... 1
  expert_parallel ................................. False
  ffn_hidden_size ................................. 5440
  fill_explicit_bubbles ........................... False
  finetune ........................................ False
  fp16 ............................................ False
  fp16_lm_cross_entropy ........................... False
  fp32_residual_connection ........................ False
  fp8 ............................................. None
  fp8_amax_compute_algo ........................... most_recent
  fp8_amax_history_len ............................ 1
  fp8_interval .................................... 1
  fp8_margin ...................................... 0
  fp8_wgrad ....................................... True
  global_batch_size ............................... 2048
  gradient_accumulation_fusion .................... True
  group_query_attention ........................... False
  head_lr_mult .................................... 1.0
  hidden_dropout .................................. 0.0
  hidden_size ..................................... 2048
  hysteresis ...................................... 2
  ict_head_size ................................... None
  ict_load ........................................ None
  img_h ........................................... 224
  img_w ........................................... 224
  indexer_batch_size .............................. 128
  indexer_log_interval ............................ 1000
  inference_batch_times_seqlen_threshold .......... 512
  init_method_std ................................. 0.01
  init_method_xavier_uniform ...................... False
  initial_loss_scale .............................. 4294967296
  iter_per_epoch .................................. 1250
  kv_channels ..................................... 64
  lazy_mpu_init ................................... None
  load ............................................ /home/data/shared/checkpoints/MET-EXP/1F1B-MET-1B-2-EXIT-6-12-0.25-0.5-300B
  load_iteration .................................. 0
  local_rank ...................................... 0
  log_batch_size_to_tracker ....................... False
  log_interval .................................... 5
  log_learning_rate_to_tracker .................... True
  log_loss_scale_to_tracker ....................... True
  log_memory_to_tracker ........................... False
  log_num_zeros_in_grad ........................... False
  log_params_norm ................................. False
  log_timers_to_tracker ........................... True
  log_validation_ppl_to_tracker ................... False
  log_world_size_to_tracker ....................... False
  loss_scale ...................................... None
  loss_scale_window ............................... 1000
  lr .............................................. 0.0002
  lr_decay_iters .................................. None
  lr_decay_samples ................................ None
  lr_decay_style .................................. cosine
  lr_warmup_fraction .............................. None
  lr_warmup_init .................................. 0.0
  lr_warmup_iters ................................. 0
  lr_warmup_samples ............................... 0
  make_vocab_size_divisible_by .................... 128
  mask_factor ..................................... 1.0
  mask_prob ....................................... 0.15
  mask_type ....................................... random
  masked_softmax_fusion ........................... False
  max_position_embeddings ......................... 2048
  max_tokens_to_oom ............................... 12000
  merge_file ...................................... None
  micro_batch_size ................................ 4
  min_loss_scale .................................. 1.0
  min_lr .......................................... 2e-05
  mmap_warmup ..................................... False
  model_spec ...................................... None
  no_load_optim ................................... True
  no_load_rng ..................................... True
  no_persist_layer_norm ........................... False
  no_save_optim ................................... True
  no_save_rng ..................................... True
  norm_epsilon .................................... 1e-05
  normalization ................................... LayerNorm
  num_attention_heads ............................. 32
  num_channels .................................... 3
  num_classes ..................................... 1000
  num_experts ..................................... None
  num_fill_cooldown_microbatches .................. 0
  num_fill_warmup_microbatches .................... 0
  num_layers ...................................... 24
  num_layers_per_virtual_pipeline_stage ........... None
  num_query_groups ................................ 1
  num_workers ..................................... 2
  onnx_safe ....................................... None
  openai_gelu ..................................... False
  optimizer ....................................... adam
  output_bert_embeddings .......................... False
  overlap_grad_reduce ............................. False
  overlap_p2p_comm ................................ False
  override_opt_param_scheduler .................... False
  padded_vocab_size ............................... 32128
  params_dtype .................................... torch.bfloat16
  patch_dim ....................................... 16
  perform_initialization .......................... False
  pipeline_model_parallel_size .................... 2
  pipeline_model_parallel_split_rank .............. None
  position_embedding_type ......................... rope
  pre_exit ........................................ False
  profile ......................................... False
  profile_ranks ................................... [0]
  profile_step_end ................................ 12
  profile_step_start .............................. 10
  query_in_block_prob ............................. 0.1
  rampup_batch_size ............................... None
  rank ............................................ 0
  recompute_granularity ........................... None
  recompute_method ................................ None
  recompute_num_layers ............................ None
  reset_attention_mask ............................ False
  reset_position_ids .............................. False
  retriever_report_topk_accuracies ................ []
sending embeddings
  retriever_score_scaling ......................... False
  retriever_seq_length ............................ 256
  retro_add_retriever ............................. False
  retro_cyclic_train_iters ........................ None
  retro_encoder_attention_dropout ................. 0.1
  retro_encoder_hidden_dropout .................... 0.1
  retro_encoder_layers ............................ 2
  retro_num_neighbors ............................. 2
  retro_num_retrieved_chunks ...................... 2
  retro_return_doc_ids ............................ False
  retro_workdir ................................... None
  rotary_percent .................................. 1.0
  rotary_seq_len_interpolation_factor ............. None
  sample_rate ..................................... 1.0
  save ............................................ /workspace/ckpt/EE-LLM-1B-dj-refine-300B
  save_interval ................................... 1
  scatter_gather_tensors_in_pipeline .............. True
  seed ............................................ 1234
  seq_length ...................................... 2048
  sequence_parallel ............................... False
  sgd_momentum .................................... 0.9
  short_seq_prob .................................. 0.1
  skip_train ...................................... False
  split ........................................... 990,9,1
  squared_relu .................................... False
  standalone_embedding_stage ...................... False
  start_weight_decay .............................. 0.1
  swiglu .......................................... True
  swin_backbone_type .............................. tiny
  tensor_model_parallel_size ...................... 1
  tensorboard_dir ................................. None
  tensorboard_queue_size .......................... 1000
  test_data_path .................................. None
  timing_log_level ................................ 0
  timing_log_option ............................... minmax
  titles_data_path ................................ None
  tokenizer_model ................................. None
  tokenizer_type .................................. SentencePieceTokenizer
  tracker_log_interval ............................ 1
  train_data_path ................................. None
  train_iters ..................................... None
  train_samples ................................... None
  transformer_impl ................................ local
  transformer_pipeline_model_parallel_size ........ 2
  tune_exit ....................................... False
  tune_exit_pipeline_parallel_size ................ 1
  untie_embeddings_and_output_weights ............. False
  untie_exit_output_weights ....................... False
  use_checkpoint_args ............................. False
  use_checkpoint_opt_param_scheduler .............. False
  use_cpu_initialization .......................... True
  use_distributed_optimizer ....................... False
  use_dynamic_exit_layer_weight ................... False
  use_exit_block .................................. False
  use_exit_mlp .................................... False
  use_exit_norm ................................... False
  use_flash_attn .................................. True
  use_mcore_models ................................ False
  use_one_sent_docs ............................... False
  use_ring_exchange_p2p ........................... False
  use_rotary_position_embeddings .................. False
  valid_data_path ................................. None
  variable_seq_lengths ............................ False
  virtual_pipeline_model_parallel_size ............ None
  vision_backbone_type ............................ vit
  vision_pretraining .............................. False
  vision_pretraining_type ......................... classify
  vocab_extra_ids ................................. 0
  vocab_file ...................................... None
  vocab_size ...................................... None
  wandb_exp_name .................................. default
  wandb_group ..................................... 1F1B-MET-1B-2-EXIT-6-12-0.25-0.5-300B
  wandb_project ................................... MET-EXP
  wandb_save_dir .................................. 
  weight_decay .................................... 0.1
  weight_decay_incr_style ......................... constant
  world_size ...................................... 2
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 512
Setting consumed_train_samples to 147456000 and consumed_valid_samples to 1228800
sending transformer layer 0
sending transformer layer 1
convert_parallelism.sh: line 16: 104236 Bus error               (core dumped) python $MEGATRON_ROOT_PATH/tools/checkpoint/util.py --model-type EarlyExitGPT --load-dir $LOAD_DIR --save-dir $SAVE_DIR --target-tensor-parallel-size $TP --target-pipeline-parallel-size $PP --megatron-path $MEGATRON_ROOT_PATH
```

**Environment (please complete the following information):**
Using the nvcr.io/nvidia/pytorch:22.12-py3 docker 
 - Megatron-LM commit ID: dev branch
 - PyTorch version: 1.14.0a0+410ce96
 - CUDA version: 12.2
 - NCCL version
System: 2x A100 SXM4

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by pan-x-c** [comment]
It seems like a hardware error.  You can try to set the shared memory `--shm-size` of your docker container to a large value, such as `32g`.

**Comment by CPA872** [comment]
Thank you. This resolves the problem.
